name: build_jetson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_jetson:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true      

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build RETINIFY with Jetson TensorRT
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          nvcr.io/nvidia/l4t-tensorrt:r10.3.0-devel \
          bash -c "
            set -e

            echo '=== TensorRT Info ==='
            nvcc --version

            echo '=== Container Info ==='
            cat /etc/os-release | grep VERSION

            echo '=== Install Dependencies ==='
            apt update && apt install -y git cmake build-essential

            echo '=== Initialize Submodules ==='
            git config --global --add safe.directory /workspace
            git submodule update --init --recursive

            echo '=== Build RETINIFY ==='
            ./build.sh --install --gpu            
          "